### ISSUE TITLE
Need source

### ISSUE THREAD

**Issue by JimmyDansbo** [joolin1/CommanderX16#1]
I would love to see the source code for the PiskelC2Bin.exe file. I don't understand how it transforms the PiskelC code to binary. 
I created a PiskelC file where the first 16 pixels had the 16 different colors and I can see that in the bin file, but I also added the same different colors to the bottom right of my "sprite" and in the bin file there is no indication that there should be a gap between the first pixels and the last pixels

**Comment by joolin1** [comment]
No problem! I added the source code. If you're familiar with .NET and C# you can just create a command line project and use my file program.cs instead of the one genereted by the IDE. (I must take some time and see how github really works and start adding other programs.).
 It has worked fine for me. But you can't use black because it becomes transparent...

**Comment by JimmyDansbo** [comment]
Well, when no color is not an option, and black becomes transparent, then I get it :)
I was thinking of writing a web-application that can transform the data. That way it will work for any platform.
