### ISSUE TITLE
Strange behaviour around 0x00000000 values

### ISSUE THREAD

**Issue by JimmyDansbo** [joolin1/CommanderX16#2]
I think there must be some sort of mistake in the PiskelC2Bin.exe program. It seems that none of the transparent pixels (0x00000000) get written to the binary file.

In the exported C file, alle fields are represented with a hexadecimal string, but for some reason all values with 0x00000000 just gets skipped and the resulting binary file only has the bytes that has actual colors.

Not sure if the problem is with the Dictionary or with the Regex.Match.

Or maybe, it is just me that is misunderstanding something ?

**Comment by joolin1** [comment]
The problem is that the piskel  file has color data for 16 colors (beginning with "0xff..." plus transparent (beginning with 0x00...). The 4bpp mode in CommanderX16 on the other hand just has 16 colors and the first one is by design transparent. That means that black (number 0 in the C64 palette) becomes transparent. It also means that transparent (=0x00000000) also is mapped to color 0. There is not much else to do (?). You can see exactly how this works in the Dictionary<string,byte> I use for mapping.

**Comment by JimmyDansbo** [comment]
[newPiskel.c.txt](https://github.com/joolin1/CommanderX16/files/3916284/newPiskel.c.txt)
Try converting the attached file with your program... It does not produce a binary file of 32x32 pixels

**Comment by joolin1** [comment]
It works when I try. You get a file of 512 bytes. 32 x 32 = 1024 byt every byte contains two pixels (4bpp = 4 bits per pixel) which gives a total size of 512 bytes.

**Comment by JimmyDansbo** [comment]
Hah, it's when I run it in wine on linux. Sorry, my mistake
